ACCOUNTS:
    AMEX:
        - Business Prime
    Apple:
        - Mastercard
    Chase:
        - Checking
        - Prime Visa
    Citi:
        - Costco Visa
    Discover:
        - Checking
        - Savings
    Paypal:
        - Mastercard
        - Balance
    Synchrony:
        - Prime
    Venmo:
        - Balance
