accounts:
    AMEX:
        - Business Prime
    Apple:
        - Mastercard
    Chase:
        - Prime Visa
        - Checking
    Citi:
        - Costco Visa
    Discover:
        - Checking
        - Savings
    Paypal:
        - Mastercard
        - Balance
    Synchrony:
        - Prime
    Venmo:
        - Balance

categories:
    - Books
    - Clothing
    - Debt
    - Education
    - Entertainment
    - Food
    - Games
    - Gas
    - Groceries
    - Gifts
    - Housing
    - Insurance
    - Medical
    - Merchandise
    - Personal
    - Plants
    - Software
    - Transportation
    - Utilities
    - Work
    - Zappies
    - Other

format:
    header:
        - Date
        - Description
        - Amount
        - Category
        - Faye
        - Oliver
        - Monthly
        - Annual
    AMEX:
        - Date
        - Description
        - Amount
